(deftheme geo-dark
  "Based on monokai-dark. Created 2016-03-09.")

(custom-theme-set-variables
 'geo-dark
 '(display-battery-mode t)
 '(rich-minority-mode t)
 '(ansi-color-names-vector ["#272822" "#f92672" "#a6e22e" "#f4bf75" "#66d9ef" "#ae81ff" "#66d9ef" "#f8f8f2"])
 '(evil-indent-convert-tabs t)
 '(ido-mode (quote both))
 '(indent-tabs-mode nil)
 '(js2-basic-offset 2)
 '(js2-missing-semi-one-line-override t)
 '(js2-mode-show-parse-errors nil)
 '(js2-strict-missing-semi-warning nil)
 '(fringe-mode (quote (nil . 0))))

(custom-theme-set-faces
 'geo-dark
 '(default ((t (:background "#272822" :foreground "#f8f8f2"))))
 '(fringe ((t (:background "#49483e"))))
 '(mode-line-inactive ((t (:background "#383830" :foreground "#75715e" :box nil))))
 '(mode-line ((t (:background "#49483e" :foreground "#a59f85" :box nil))))
 '(border ((t (:background "#75715e"))))
 '(cursor ((t (:background "#f92672"))))
 '(highlight ((t (:background "#383830"))))
 '(link ((t (:foreground nil :underline t))))
 '(link-visited ((t (:foreground "#ae81ff"))))
 '(minibuffer-prompt ((t (:foreground "#66d9ef"))))
 '(mode-line-buffer-id ((t (:foreground "#ae81ff" :background nil))))
 '(mode-line-emphasis ((t (:foreground "#f5f4f1" :slant italic))))
 '(mode-line-highlight ((t (:foreground "#ae81ff" :box nil :weight bold))))
 '(region ((t (:background "#49483e"))))
 '(secondary-selection ((t (:background "#75715e"))))
 '(error ((t (:foreground "#f92672" :weight bold))))
 '(flycheck-fringe-error ((t (:foreground "#f92672" :weight bold))))
 '(warning ((t (:foreground "#fd971f" :weight bold))))
 '(success ((t (:foreground "#a6e22e" :weight bold))))
 '(header-line ((t (:inherit mode-line :foreground "#ae81ff" :background nil))))
 '(font-lock-builtin-face ((t (:foreground "#a1efe4"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#49483e"))))
 '(font-lock-comment-face ((t (:foreground "#75715e"))))
 '(font-lock-constant-face ((t (:foreground "#fd971f"))))
 '(font-lock-doc-face ((t (:foreground "#a59f85"))))
 '(font-lock-function-name-face ((t (:foreground "#66d9ef"))))
 '(font-lock-keyword-face ((t (:foreground "#ae81ff"))))
 '(font-lock-negation-char-face ((t (:foreground "#a6e22e"))))
 '(font-lock-preprocessor-face ((t (:foreground "#66d9ef"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#f4bf75"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#ae81ff"))))
 '(font-lock-string-face ((t (:foreground "#a6e22e"))))
 '(font-lock-type-face ((t (:foreground "#f4bf75"))))
 '(font-lock-variable-name-face ((t (:foreground "#a1efe4"))))
 '(font-lock-warning-face ((t (:foreground "#f92672"))))
 '(linum ((t (:background "#383830" :foreground "#75715e"))))
 '(match ((t (:foreground "#66d9ef" :background "#383830" :inverse-video t))))
 '(isearch ((t (:foreground "#f4bf75" :background "#383830" :inverse-video t))))
 '(lazy-highlight ((t (:foreground "#a1efe4" :background "#383830" :inverse-video t))))
 '(isearch-fail ((t (:background "#383830" :inherit font-lock-warning-face :inverse-video t))))
 '(ido-subdir ((t (:foreground "#a59f85"))))
 '(ido-first-match ((t (:foreground "#fd971f" :weight bold))))
 '(ido-only-match ((t (:foreground "#f92672" :weight bold))))
 '(ido-indicator ((t (:foreground "#f92672" :background "#383830"))))
 '(ido-virtual ((t (:foreground "#a59f85"))))
 '(which-func ((t (:foreground "#66d9ef" :background nil :weight bold))))
 '(trailing-whitespace ((t (:background "#a1efe4" :foreground "#f4bf75"))))
 '(whitespace-empty ((t (:foreground "#f92672" :background "#f4bf75"))))
 '(whitespace-hspace ((t (:background "#a59f85" :foreground "#a59f85"))))
 '(whitespace-indentation ((t (:background "#f4bf75" :foreground "#f92672"))))
 '(whitespace-line ((t (:background "#383830" :foreground "#cc6633"))))
 '(whitespace-newline ((t (:foreground "#a59f85"))))
 '(whitespace-space ((t (:background "#383830" :foreground "#a59f85"))))
 '(whitespace-space-after-tab ((t (:background "#f4bf75" :foreground "#f92672"))))
 '(whitespace-space-before-tab ((t (:background "#fd971f" :foreground "#f92672"))))
 '(whitespace-tab ((t (:background "#a59f85" :foreground "#a59f85"))))
 '(whitespace-trailing ((t (:background "#f92672" :foreground "#f4bf75"))))
 '(show-paren-match ((t (:background "#66d9ef" :foreground "#75715e"))))
 '(show-paren-mismatch ((t (:background "#fd971f" :foreground "#75715e"))))
 '(diff-added ((t (:foreground "#a6e22e"))))
 '(diff-changed ((t (:foreground "#f4bf75"))))
 '(diff-removed ((t (:foreground "#f92672"))))
 '(diff-header ((t (:background "#383830"))))
 '(diff-file-header ((t (:background "#49483e"))))
 '(diff-hunk-header ((t (:background "#383830" :foreground "#ae81ff"))))
 '(eldoc-highlight-function-argument ((t (:foreground "#a6e22e" :weight bold))))
 '(undo-tree-visualizer-default-face ((t (:foreground "#f5f4f1"))))
 '(undo-tree-visualizer-current-face ((t (:foreground "#a6e22e" :weight bold))))
 '(undo-tree-visualizer-active-branch-face ((t (:foreground "#f92672"))))
 '(undo-tree-visualizer-register-face ((t (:foreground "#f4bf75"))))
 '(widget-button ((t (:underline t))))
 '(widget-field ((t (:background "#75715e" :box (:line-width 1 :color "#f5f4f1")))))
 '(compilation-column-number ((t (:foreground "#f4bf75"))))
 '(compilation-line-number ((t (:foreground "#f4bf75"))))
 '(compilation-mode-line-exit ((t (:foreground "#a6e22e"))))
 '(compilation-mode-line-fail ((t (:foreground "#f92672"))))
 '(compilation-mode-line-run ((t (:foreground "#66d9ef"))))
 '(org-agenda-structure ((t (:foreground "#ae81ff"))))
 '(org-agenda-date ((t (:foreground "#66d9ef" :underline nil))))
 '(org-agenda-done ((t (:foreground "#a6e22e"))))
 '(org-agenda-dimmed-todo-face ((t (:foreground "#a59f85"))))
 '(org-block ((t (:foreground "#fd971f"))))
 '(org-code ((t (:foreground "#f4bf75"))))
 '(org-column ((t (:background "#383830"))))
 '(org-column-title ((t (:inherit org-column :weight bold :underline t))))
 '(org-date ((t (:foreground "#ae81ff" :underline t))))
 '(org-document-info ((t (:foreground "#a1efe4"))))
 '(org-document-info-keyword ((t (:foreground "#a6e22e"))))
 '(org-document-title ((t (:weight bold :foreground "#fd971f" :height 1.44))))
 '(org-done ((t (:foreground "#a6e22e"))))
 '(org-ellipsis ((t (:foreground "#a59f85"))))
 '(org-footnote ((t (:foreground "#a1efe4"))))
 '(org-formula ((t (:foreground "#f92672"))))
 '(org-hide ((t (:foreground "#75715e"))))
 '(org-link ((t (:foreground "#66d9ef"))))
 '(org-scheduled ((t (:foreground "#a6e22e"))))
 '(org-scheduled-previously ((t (:foreground "#fd971f"))))
 '(org-scheduled-today ((t (:foreground "#a6e22e"))))
 '(org-special-keyword ((t (:foreground "#fd971f"))))
 '(org-table ((t (:foreground "#ae81ff"))))
 '(org-todo ((t (:foreground "#f92672"))))
 '(org-upcoming-deadline ((t (:foreground "#fd971f"))))
 '(org-warning ((t (:weight bold :foreground "#f92672"))))
 '(message-header-other ((t (:foreground nil :background nil :weight normal))))
 '(message-header-subject ((t (:inherit message-header-other :weight bold :foreground "#f4bf75"))))
 '(message-header-to ((t (:inherit message-header-other :weight bold :foreground "#fd971f"))))
 '(message-header-cc ((t (:inherit message-header-to :foreground nil))))
 '(message-header-name ((t (:foreground "#66d9ef" :background nil))))
 '(message-header-newsgroups ((t (:foreground "#a1efe4" :background nil :slant normal))))
 '(message-separator ((t (:foreground "#ae81ff"))))
 '(erc-direct-msg-face ((t (:foreground "#fd971f"))))
 '(erc-error-face ((t (:foreground "#f92672"))))
 '(erc-input-face ((t (:foreground "#a6e22e"))))
 '(erc-keyword-face ((t (:foreground "#f4bf75"))))
 '(erc-current-nick-face ((t (:foreground "#a6e22e"))))
 '(erc-my-nick-face ((t (:foreground "#a6e22e"))))
 '(erc-nick-default-face ((t (:weight normal :foreground "#ae81ff"))))
 '(erc-nick-msg-face ((t (:weight normal :foreground "#f4bf75"))))
 '(erc-notice-face ((t (:foreground "#a59f85"))))
 '(erc-pal-face ((t (:foreground "#fd971f"))))
 '(erc-prompt-face ((t (:foreground "#66d9ef"))))
 '(erc-timestamp-face ((t (:foreground "#a1efe4"))))
 '(helm-action ((t (:foreground "#f8f8f2"))))
 '(helm-buffer-directory ((t (:foreground "#a59f85" :background nil :weight bold))))
 '(helm-buffer-file ((t (:foreground "#a1efe4"))))
 '(helm-buffer-not-saved ((t (:foreground "#f92672"))))
 '(helm-buffer-process ((t (:foreground "#75715e"))))
 '(helm-buffer-saved-out ((t (:foreground "#cc6633"))))
 '(helm-buffer-size ((t (:foreground "#fd971f"))))
 '(helm-candidate-number ((t (:foreground "#272822" :background "#fd971f"))))
 '(helm-ff-directory ((t (:foreground "#a59f85" :background nil :weight bold))))
 '(helm-ff-executable ((t (:foreground "#a6e22e"))))
 '(helm-ff-file ((t (:foreground "#a1efe4"))))
 '(helm-ff-invalid-symlink ((t (:foreground "#272822" :background "#f92672"))))
 '(helm-ff-prefix ((t (:foreground nil :background nil))))
 '(helm-ff-symlink ((t (:foreground "#272822" :background "#a1efe4"))))
 '(helm-grep-cmd-line ((t (:foreground "#a6e22e"))))
 '(helm-grep-file ((t (:foreground "#a1efe4"))))
 '(helm-grep-finish ((t (:foreground "#272822" :background "#fd971f"))))
 '(helm-grep-lineno ((t (:foreground "#75715e"))))
 '(helm-grep-match ((t (:foreground "#f4bf75"))))
 '(helm-header ((t (:foreground "#f4bf75" :background "#272822" :underline nil))))
 '(helm-match ((t (:foreground "#f4bf75"))))
 '(helm-moccur-buffer ((t (:foreground "#a1efe4"))))
 '(helm-selection ((t (:foreground nil :background "#49483e" :underline nil))))
 '(helm-selection-line ((t (:foreground nil :background "#49483e"))))
 '(helm-separator ((t (:foreground "#49483e"))))
 '(helm-source-header ((t (:foreground "#f8f8f2" :background "#383830" :weight bold))))
 '(helm-visible-mark ((t (:foreground "#272822" :background "#a6e22e"))))
 '(custom-variable-tag ((t (:foreground "#66d9ef"))))
 '(custom-group-tag ((t (:foreground "#66d9ef"))))
 '(custom-state ((t (:foreground "#a6e22e")))))

(provide-theme 'geo-dark)
